// Copyright (c) 2022-present INESC-ID.
// Distributed under the MIT license that can be found in the LICENSE file.

#ifdef CPP2RUST_USE_INCLUDES
#include <errno.h>
#endif

int *CPP2RUST_EXPR_RULE(1)(void) { return cpp2rust_errno(); }

int CPP2RUST_EXPR_RULE(2)(void) { return E2BIG; }
int CPP2RUST_EXPR_RULE(3)(void) { return EACCES; }
int CPP2RUST_EXPR_RULE(4)(void) { return EADDRINUSE; }
int CPP2RUST_EXPR_RULE(5)(void) { return EADDRNOTAVAIL; }
int CPP2RUST_EXPR_RULE(6)(void) { return EAFNOSUPPORT; }
int CPP2RUST_EXPR_RULE(7)(void) { return EAGAIN; }
int CPP2RUST_EXPR_RULE(8)(void) { return EALREADY; }
int CPP2RUST_EXPR_RULE(9)(void) { return EBADF; }
int CPP2RUST_EXPR_RULE(10)(void) { return EBADMSG; }
int CPP2RUST_EXPR_RULE(11)(void) { return EBUSY; }
int CPP2RUST_EXPR_RULE(12)(void) { return ECANCELED; }
int CPP2RUST_EXPR_RULE(13)(void) { return ECHILD; }
int CPP2RUST_EXPR_RULE(14)(void) { return ECONNABORTED; }
int CPP2RUST_EXPR_RULE(15)(void) { return ECONNREFUSED; }
int CPP2RUST_EXPR_RULE(16)(void) { return ECONNRESET; }
int CPP2RUST_EXPR_RULE(17)(void) { return EDEADLK; }
int CPP2RUST_EXPR_RULE(18)(void) { return EDESTADDRREQ; }
int CPP2RUST_EXPR_RULE(19)(void) { return EDOM; }
int CPP2RUST_EXPR_RULE(20)(void) { return EDQUOT; }
int CPP2RUST_EXPR_RULE(21)(void) { return EEXIST; }
int CPP2RUST_EXPR_RULE(22)(void) { return EFAULT; }
int CPP2RUST_EXPR_RULE(23)(void) { return EFBIG; }
int CPP2RUST_EXPR_RULE(24)(void) { return EHOSTDOWN; }
int CPP2RUST_EXPR_RULE(25)(void) { return EHOSTUNREACH; }
int CPP2RUST_EXPR_RULE(26)(void) { return EIDRM; }
int CPP2RUST_EXPR_RULE(27)(void) { return EILSEQ; }
int CPP2RUST_EXPR_RULE(28)(void) { return EINPROGRESS; }
int CPP2RUST_EXPR_RULE(29)(void) { return EINTR; }
int CPP2RUST_EXPR_RULE(30)(void) { return EINVAL; }
int CPP2RUST_EXPR_RULE(31)(void) { return EIO; }
int CPP2RUST_EXPR_RULE(32)(void) { return EISCONN; }
int CPP2RUST_EXPR_RULE(33)(void) { return EISDIR; }
int CPP2RUST_EXPR_RULE(34)(void) { return ELOOP; }
int CPP2RUST_EXPR_RULE(35)(void) { return EMFILE; }
int CPP2RUST_EXPR_RULE(36)(void) { return EMLINK; }
int CPP2RUST_EXPR_RULE(37)(void) { return EMSGSIZE; }
int CPP2RUST_EXPR_RULE(38)(void) { return EMULTIHOP; }
int CPP2RUST_EXPR_RULE(39)(void) { return ENAMETOOLONG; }
int CPP2RUST_EXPR_RULE(40)(void) { return ENETDOWN; }
int CPP2RUST_EXPR_RULE(41)(void) { return ENETRESET; }
int CPP2RUST_EXPR_RULE(42)(void) { return ENETUNREACH; }
int CPP2RUST_EXPR_RULE(43)(void) { return ENFILE; }
int CPP2RUST_EXPR_RULE(44)(void) { return ENOBUFS; }
int CPP2RUST_EXPR_RULE(45)(void) { return ENODATA; }
int CPP2RUST_EXPR_RULE(46)(void) { return ENODEV; }
int CPP2RUST_EXPR_RULE(47)(void) { return ENOENT; }
int CPP2RUST_EXPR_RULE(48)(void) { return ENOEXEC; }
int CPP2RUST_EXPR_RULE(49)(void) { return ENOLCK; }
int CPP2RUST_EXPR_RULE(50)(void) { return ENOLINK; }
int CPP2RUST_EXPR_RULE(51)(void) { return ENOMEM; }
int CPP2RUST_EXPR_RULE(52)(void) { return ENOMSG; }
int CPP2RUST_EXPR_RULE(53)(void) { return ENOPROTOOPT; }
int CPP2RUST_EXPR_RULE(54)(void) { return ENOSPC; }
int CPP2RUST_EXPR_RULE(55)(void) { return ENOSR; }
int CPP2RUST_EXPR_RULE(56)(void) { return ENOSTR; }
int CPP2RUST_EXPR_RULE(57)(void) { return ENOSYS; }
int CPP2RUST_EXPR_RULE(58)(void) { return ENOTCONN; }
int CPP2RUST_EXPR_RULE(59)(void) { return ENOTDIR; }
int CPP2RUST_EXPR_RULE(60)(void) { return ENOTEMPTY; }
int CPP2RUST_EXPR_RULE(61)(void) { return ENOTRECOVERABLE; }
int CPP2RUST_EXPR_RULE(62)(void) { return ENOTSOCK; }
int CPP2RUST_EXPR_RULE(63)(void) { return ENOTSUP; }
int CPP2RUST_EXPR_RULE(64)(void) { return ENOTBLK; }
int CPP2RUST_EXPR_RULE(65)(void) { return ENOTTY; }
int CPP2RUST_EXPR_RULE(66)(void) { return ENXIO; }
int CPP2RUST_EXPR_RULE(67)(void) { return EOPNOTSUPP; }
int CPP2RUST_EXPR_RULE(68)(void) { return EOVERFLOW; }
int CPP2RUST_EXPR_RULE(69)(void) { return EOWNERDEAD; }
int CPP2RUST_EXPR_RULE(70)(void) { return EPERM; }
int CPP2RUST_EXPR_RULE(71)(void) { return EPFNOSUPPORT; }
int CPP2RUST_EXPR_RULE(72)(void) { return EPIPE; }
int CPP2RUST_EXPR_RULE(73)(void) { return EPROTO; }
int CPP2RUST_EXPR_RULE(74)(void) { return EPROTONOSUPPORT; }
int CPP2RUST_EXPR_RULE(75)(void) { return EPROTOTYPE; }
int CPP2RUST_EXPR_RULE(76)(void) { return ERANGE; }
int CPP2RUST_EXPR_RULE(77)(void) { return EREMOTE; }
int CPP2RUST_EXPR_RULE(78)(void) { return EROFS; }
int CPP2RUST_EXPR_RULE(79)(void) { return ESHUTDOWN; }
int CPP2RUST_EXPR_RULE(80)(void) { return ESOCKTNOSUPPORT; }
int CPP2RUST_EXPR_RULE(81)(void) { return ESPIPE; }
int CPP2RUST_EXPR_RULE(82)(void) { return ESRCH; }
int CPP2RUST_EXPR_RULE(83)(void) { return ESTALE; }
int CPP2RUST_EXPR_RULE(84)(void) { return ETIME; }
int CPP2RUST_EXPR_RULE(85)(void) { return ETIMEDOUT; }
int CPP2RUST_EXPR_RULE(86)(void) { return ETOOMANYREFS; }
int CPP2RUST_EXPR_RULE(87)(void) { return ETXTBSY; }
int CPP2RUST_EXPR_RULE(88)(void) { return EUSERS; }
int CPP2RUST_EXPR_RULE(89)(void) { return EWOULDBLOCK; }
int CPP2RUST_EXPR_RULE(90)(void) { return EXDEV; }

#if defined(__linux__)
int CPP2RUST_EXPR_RULE(91)(void) { return EADV; }
int CPP2RUST_EXPR_RULE(92)(void) { return EBADE; }
int CPP2RUST_EXPR_RULE(93)(void) { return EBADFD; }
int CPP2RUST_EXPR_RULE(94)(void) { return EBADR; }
int CPP2RUST_EXPR_RULE(95)(void) { return EBADRQC; }
int CPP2RUST_EXPR_RULE(96)(void) { return EBADSLT; }
int CPP2RUST_EXPR_RULE(97)(void) { return EBFONT; }
int CPP2RUST_EXPR_RULE(98)(void) { return ECHRNG; }
int CPP2RUST_EXPR_RULE(99)(void) { return ECOMM; }
int CPP2RUST_EXPR_RULE(100)(void) { return EDEADLOCK; }
int CPP2RUST_EXPR_RULE(101)(void) { return EDOTDOT; }
int CPP2RUST_EXPR_RULE(102)(void) { return EHWPOISON; }
int CPP2RUST_EXPR_RULE(103)(void) { return EISNAM; }
int CPP2RUST_EXPR_RULE(104)(void) { return EKEYEXPIRED; }
int CPP2RUST_EXPR_RULE(105)(void) { return EKEYREJECTED; }
int CPP2RUST_EXPR_RULE(106)(void) { return EKEYREVOKED; }
int CPP2RUST_EXPR_RULE(107)(void) { return EL2HLT; }
int CPP2RUST_EXPR_RULE(108)(void) { return EL2NSYNC; }
int CPP2RUST_EXPR_RULE(109)(void) { return EL3HLT; }
int CPP2RUST_EXPR_RULE(110)(void) { return EL3RST; }
int CPP2RUST_EXPR_RULE(111)(void) { return ELIBACC; }
int CPP2RUST_EXPR_RULE(112)(void) { return ELIBBAD; }
int CPP2RUST_EXPR_RULE(113)(void) { return ELIBEXEC; }
int CPP2RUST_EXPR_RULE(114)(void) { return ELIBMAX; }
int CPP2RUST_EXPR_RULE(115)(void) { return ELIBSCN; }
int CPP2RUST_EXPR_RULE(116)(void) { return ELNRNG; }
int CPP2RUST_EXPR_RULE(117)(void) { return EMEDIUMTYPE; }
int CPP2RUST_EXPR_RULE(118)(void) { return ENAVAIL; }
int CPP2RUST_EXPR_RULE(119)(void) { return ENOANO; }
int CPP2RUST_EXPR_RULE(120)(void) { return ENOCSI; }
int CPP2RUST_EXPR_RULE(121)(void) { return ENOKEY; }
int CPP2RUST_EXPR_RULE(122)(void) { return ENOMEDIUM; }
int CPP2RUST_EXPR_RULE(123)(void) { return ENONET; }
int CPP2RUST_EXPR_RULE(124)(void) { return ENOPKG; }
int CPP2RUST_EXPR_RULE(125)(void) { return ENOTNAM; }
int CPP2RUST_EXPR_RULE(126)(void) { return ENOTUNIQ; }
int CPP2RUST_EXPR_RULE(127)(void) { return EREMCHG; }
int CPP2RUST_EXPR_RULE(128)(void) { return EREMOTEIO; }
int CPP2RUST_EXPR_RULE(129)(void) { return ERESTART; }
int CPP2RUST_EXPR_RULE(130)(void) { return ERFKILL; }
int CPP2RUST_EXPR_RULE(131)(void) { return ESRMNT; }
int CPP2RUST_EXPR_RULE(132)(void) { return ESTRPIPE; }
int CPP2RUST_EXPR_RULE(133)(void) { return EUCLEAN; }
int CPP2RUST_EXPR_RULE(134)(void) { return EUNATCH; }
int CPP2RUST_EXPR_RULE(135)(void) { return EXFULL; }
#elif defined(__APPLE__)
int CPP2RUST_EXPR_RULE(136)(void) { return EAUTH; }
int CPP2RUST_EXPR_RULE(137)(void) { return EBADARCH; }
int CPP2RUST_EXPR_RULE(138)(void) { return EBADEXEC; }
int CPP2RUST_EXPR_RULE(139)(void) { return EBADMACHO; }
int CPP2RUST_EXPR_RULE(140)(void) { return EBADRPC; }
int CPP2RUST_EXPR_RULE(141)(void) { return EDEVERR; }
int CPP2RUST_EXPR_RULE(142)(void) { return EFTYPE; }
int CPP2RUST_EXPR_RULE(143)(void) { return ENEEDAUTH; }
int CPP2RUST_EXPR_RULE(144)(void) { return ENOATTR; }
int CPP2RUST_EXPR_RULE(145)(void) { return ENOPOLICY; }
int CPP2RUST_EXPR_RULE(146)(void) { return EPROCLIM; }
int CPP2RUST_EXPR_RULE(147)(void) { return EPROCUNAVAIL; }
int CPP2RUST_EXPR_RULE(148)(void) { return EPROGMISMATCH; }
int CPP2RUST_EXPR_RULE(149)(void) { return EPROGUNAVAIL; }
int CPP2RUST_EXPR_RULE(150)(void) { return EPWROFF; }
int CPP2RUST_EXPR_RULE(151)(void) { return EQFULL; }
int CPP2RUST_EXPR_RULE(152)(void) { return ERPCMISMATCH; }
int CPP2RUST_EXPR_RULE(153)(void) { return ESHLIBVERS; }
#endif
